defaultNamespace: evantage
helm:
  repo: https://evantage-ws.github.io/helm-charts/
  chart: hello-kubernetes
  releaseName: hello-kubernetes
  values:
    ingress:
      host: "hello-kubernetes-${ .ClusterLabels.domain }"
    env:
      message: "I just deployed this via Fleet, it's working with a Safe Base Container Image, SUSE BCI! :-)"

