apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: space-station-control-center
  namespace: fleet-default
spec:
  branch: main
  paths:
    - space-station-control-center/helm
  repo: https://github.com/Evantage-WS/fleet-deployments
  targets:
    - clusterGroup: deploy-space-station-control-center
