apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: nettools
  namespace: fleet-default
spec:
  branch: main
  paths:
    - evantage-nettools/helm
  repo: https://github.com/Evantage-WS/fleet-deployments
  targets:
    - clusterGroup: deploy-evantage-nettools
