apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: hello-rancher
  namespace: fleet-local
spec:
  branch: main
  paths:
    - hello-rancher/helm
  repo: https://github.com/Evantage-WS/fleet-deployments
  targets:
    - clusterGroup: deploy-hello-rancher
