defaultNamespace: evantage
helm:
  repo: https://evantage-ws.github.io/helm-charts/
  chart: hello-rancher
  version: 1.0.3
  releaseName: hello-rancher
  values:
    replicaCount: 4
    app:
      localization:
        title: "Rancher Demo App"
        pets: "cows" # available pets include 'cows' and 'chameleons' and possibly 'cowmeleons'
        color: "green" # container background color (any color name from the CSS pallete)
    ingress:
      enabled: true
      # Most of the time, use hello-rancher.192.168.2.10.sslip.io, see kubeclt get ingress -n hello-rancher op de downstream server
      # Add a label on the downstream cluster with 'domain = 192.168.2.10.sslip.io'
      host: "hello-rancher-${ .ClusterLabels.domain }"
