defaultNamespace: hello-rancher
helm:
  repo: https://evantage-ws.github.io/helm-charts/
  chart: hello-rancher
  version: 1.0.1
  releaseName: hello-rancher
  values:
    replicaCount: 2
    ingress:
      enabled: true
      # Most of the time, use hello-rancher.192.168.2.10.sslip.io, see kubeclt get ingress -n hello-rancher op de downstream server
      # Add a label on the downstream cluster with 'domain = hello-rancher.192.168.2.10.sslip.io'
      host: "hello-rancher.${ .ClusterLabels.domain }"

