defaultNamespace: hello-rancher
helm:
  repo: https://evantage-ws.github.io/helm-charts/
  chart: hello-rancher
  version: 0.1.1
  releaseName: hello-rancher
  values:
    replicaCount: 2
    ingress:
      enabled: true
      host: "hello-rancher.${ .ClusterLabels.domain }"

